src/Form/ProductVariantChoiceType.php
<?php

declare(strict_types=1);

namespace Siganushka\ProductBundle\Form;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Siganushka\ProductBundle\Entity\OptionValue;
use Siganushka\ProductBundle\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductVariantChoiceType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setNormalizer('choices', function (Options $options) {
            if ($options['product'] instanceof Product) {
                return $options['product']->getOptionsMapping();
            }

            return null;
        });

        $resolver->setDefaults([
            'choice_label' => [__CLASS__, 'createChoiceLabel'],
            'choice_value' => [__CLASS__, 'createChoiceValue'],
            // 'choice_attr' => [__CLASS__, 'createChoiceAttr'],
            'choice_translation_domain' => false,
            'empty_data' => new ArrayCollection(),
            'product' => null,
        ]);

        $resolver->setAllowedTypes('product', ['null', Product::class]);
    }

    public function getParent(): string
    {
        return ChoiceType::class;
    }

    public static function createChoiceLabel(Collection $choice): string
    {
        return implode('/', $choice->map(fn (OptionValue $optionValue) => $optionValue->getText())->toArray());
    }

    public static function createChoiceValue(?Collection $choice): ?string
    {
        if (null === $choice) {
            return null;
        }

        return implode('_', $choice->map(fn (OptionValue $optionValue) => $optionValue->getCode())->toArray());
    }

    public static function createChoiceAttr(Collection $choice): array
    {
        dd($choice);
    }
}

src/Resources/views/fields.html.twig
{% block _option_values_widget %}
  {% if form.vars.allow_add %}
    <div class="mb-3">
      <button
        type="button"
        class="btn btn-primary"
        data-prototype="{{ form_widget(form.vars.prototype)|e('html_attr') }}"
        onclick="addItem(this, '{{ form.vars.id }}')">添加</button>
    </div>
  {% endif %}

  <div id="{{ form.vars.id }}" class="border-top border-bottom bg-light px-3">
    {%- for item in form %}
      {{ form_widget(item) }}
    {% endfor -%}
  </div>

  <style>
    #option_values:empty { display: none; }
  </style>

  <script>
  function addItem(event, id) {
    const collectionHolder = document.getElementById(id)

    const item = document.createElement('dev')
    item.innerHTML = event.dataset.prototype.replace(/__name__/g, collectionHolder.children.length ++)

    console.log(item.firstChild)
    collectionHolder.appendChild(item.firstChild)
  }

  function removeItem(event, id) {
    if (confirm('确定删除码？')) {
      const entry = document.getElementById(id)
      entry && entry.remove()
    }
  }
  </script>
{% endblock %}

{% block _option_values_entry_widget %}
<div id="{{ form.vars.id }}" class="row my-3">
  <div style="flex: 0 0 150px">
    {{ form_widget(form.img) }}
    {{ form_errors(form.img) }}
  </div>
  <div class="col">
    {{ form_widget(form.text) }}
    {{ form_errors(form.text) }}
  </div>
  <div class="col">
    {{ form_widget(form.sort) }}
    {{ form_errors(form.sort) }}
  </div>
  {% if form.parent.vars.allow_delete %}
    <div style="flex: 0 0 80px">
      <button
        type="button"
        class="btn btn-link text-danger px-0"
        onclick="removeItem(this, '{{ form.vars.id }}')">删除</button>
    </div>
  {% endif %}
</div>
{% endblock %}